name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            laravel: '9.*'
            testbench: '7.*'
          - php: '8.2'
            laravel: '10.*'
            testbench: '8.*'
          - php: '8.3'
            laravel: '11.*'
            testbench: '9.*'
    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer require "illuminate/http:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
      - run: composer update --prefer-dist --no-interaction --with-all-dependencies
      - run: vendor/bin/phpunit
